[[group]]
name = "Rusty Drones"

[[group]]
name = "Rolling_Drones"

[[group]]
name = "Rustbusters"

[[group]]
name = "Rust-eze"
aliases = ["Rusteze Drone"]

[[group]]
name = "Dronegowski"

[[group]]
name = "FlyPath"

[[group]]
name = "Krusty_club"

[[group]]
name = "LeDron-James"

[[group]]
name = "Rust In Peace"

[[group]]
name = "Sky Link"

[[group]]
name = "Rusty Bagel Bomber (from the 5th dimension)"
aliases = ["Bagel Bomber"]

[[group]]
name = "Bobry w locie"

[[group]]
name = "C++ enjoyers"

[[group]]
name = "Better Call Drone!"

[[group]]
name = "Rustafarian"
aliases = ["Rustafarian Drones"]

[[group]]
name = "In God (and Rust) We Trust"
aliases = ["Trust Drone"]

[[group]]
name = "Get Droned"

[[group]]
name = "Fungi"

[[group]]
name = "Devs Rage Over Nonsense Errs (D.R.O.N.E)"
aliases = ["Drone", "D_R_O_N_E"]

[[group]]
name = "Lockheed Rustin"

[[group]]
name = "Rustaceans Wit Attitudes"

[[group]]
name = "Rustastic"

[[group]]
name = "RustRoveri"

[[group]]
name = "Game of drones"

[[group]]
name = "The Null Pointer Patrol"

[[group]]
name = "Dr. Ones"

[[group]]
name = "Rust & Furious"

[[group]]
name = "Rustable"

[[group]]
name = "Krusty Crap"

[[group]]
name = "Rust do it"

[[group]]
name = "Rust"
aliases = ["Rust the group"]
